services:
  nginx:
    build:
      context: ./frontend
    ports:
      - "8000:80"
    networks:
      - webnet

  postgres:
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - webnet

networks:
  webnet: